quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=lovecraftuser
quarkus.datasource.password=lovecraftpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lovecraftlibrary

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080

quarkus.oidc.auth-server-url=http://localhost:9090/realms/lovecraft-library
quarkus.oidc.client-id=lovecraft-library-client
quarkus.oidc.credentials.secret=rxJnYy2e35IJrBitR6sCvWPGuWlk1yDI
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.token.audience=lovecraft-library-client