quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=lovecraftuser
quarkus.datasource.password=lovecraftpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lovecraftlibrary

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080